import { ElementType, OneHandWeaponCategory, Weapon } from "../../../types";

export const DAGGERS: Weapon[] = [
  {
    id: 34,
    name: 'Coutelas',
    category: OneHandWeaponCategory.DAGGER,
    cost: 4,
    damage: 3,
    rank: 0,
    weight: 1,
    recipe: [{ material: 'iron', value: 2 }],
  },
  {
    id: 51,
    name: 'Dague',
    category: OneHandWeaponCategory.DAGGER,
    cost: 4,
    damage: 3,
    rank: 1,
    weight: 1,
    bonuses: [{ stat: 'precision', value: 5 }],
    recipe: [{ material: 'iron', value: 2 }],
  },
  {
    id: 452,
    name: 'Dague courbe',
    category: OneHandWeaponCategory.DAGGER,
    cost: 4,
    damage: 3,
    rank: 2,
    weight: 1,
    bonuses: [{ stat: 'precision', value: 10 }],
  },
  {
    id: 141,
    name: 'Kandjar',
    category: OneHandWeaponCategory.DAGGER,
    cost: 4,
    damage: 3,
    rank: 3,
    weight: 1,
    bonuses: [{ stat: 'precision', value: 15 }],
    recipe: [
      { material: 'iron', value: 3 },
      { material: 'copper', value: 3 },
    ],
  },
  {
    id: 53,
    name: 'Kukri',
    category: OneHandWeaponCategory.DAGGER,
    cost: 4,
    damage: 3,
    rank: 3,
    weight: 1,
    recipe: [{ material: 'iron', value: 4 }],
    effects: [{ status: 'bleeding', value: 1 }]
  },
  {
    id: 47,
    name: 'Poignard',
    category: OneHandWeaponCategory.DAGGER,
    cost: 4,
    damage: 3,
    rank: 3,
    weight: 1,
    effects: [{ status: 'armor_penalty', value: 1 }],
    recipe: [
      { material: 'iron', value: 3 },
      { material: 'mithril', value: 2 },
    ],
  },
  {
    id: 362,
    name: 'Dague sinistre',
    category: OneHandWeaponCategory.DAGGER,
    cost: 4,
    damage: 2,
    rank: 3,
    weight: 1,
    element: ElementType.DARK,
    effects: [{ status: 'accuracy_penalty', value: 1 }],
  },
];
