import { ElementType, OneHandWeaponCategory, Weapon } from "../../../types";

export const GLOVES: Weapon[] = [
  {
    id: 357,
    name: 'Manicle embrasée',
    category: OneHandWeaponCategory.GLOVE,
    cost: 5,
    damage: 2,
    rank: 3,
    weight: 2,
    element: ElementType.FIRE,
    bonuses: [{ stat: 'armor', value: 2 }],
  },
  {
    id: 296,
    name: 'Tonfa',
    category: OneHandWeaponCategory.GLOVE,
    cost: 4,
    damage: 3,
    rank: 1,
    weight: 2,
    bonuses: [{ stat: 'armor', value: 1 }],
    recipe: [{ material: 'wood', value: 2 }],
  },
  {
    id: 453,
    name: 'Ceste',
    category: OneHandWeaponCategory.GLOVE,
    cost: 4,
    damage: 3,
    rank: 2,
    weight: 2,
    bonuses: [
      { stat: 'armor', value: 1 },
      { stat: 'evasion', value: 5 },
    ],
  },
  {
    id: 14,
    name: 'Gantelet',
    category: OneHandWeaponCategory.GLOVE,
    cost: 5,
    damage: 5,
    rank: 3,
    weight: 2,
    bonuses: [{ stat: 'armor', value: 2 }],
    effects: [{ status: 'evasion_penalty', value: 1 }],
    recipe: [
      { material: 'iron', value: 3 },
      { material: 'leather', value: 1 },
    ],
  },
  {
    id: 80,
    name: 'Griffes',
    category: OneHandWeaponCategory.GLOVE,
    cost: 4,
    damage: 2,
    rank: 3,
    weight: 2,
    bonuses: [
      { stat: 'precision', value: 10 },
      { stat: 'evasion', value: 5 },
      { stat: 'armor', value: 1 },
    ],
    recipe: [
      { material: 'iron', value: 4 },
      { material: 'teeth', value: 1 },
    ],
  },
  {
    id: 167,
    name: 'Griffes larges',
    category: OneHandWeaponCategory.GLOVE,
    cost: 4,
    damage: 4,
    rank: 3,
    weight: 2,
    bonuses: [
      { stat: 'evasion', value: 5 },
      { stat: 'armor', value: 1 },
    ],
  },
];
