import { ElementType, OneHandWeaponCategory, Weapon } from "../../../types";

export const SPELL_FOCUSES: Weapon[] = [
  {
    id: 23,
    name: 'Sceptre',
    category: OneHandWeaponCategory.SPELL_FOCUS,
    cost: 4,
    damage: 0,
    rank: 1,
    weight: 2,
    bonuses: [{ stat: 'magicDamage', value: 4 }],
    recipe: [{ material: 'wood', value: 2 }],
  },
  {
    id: 441,
    name: 'Baguette',
    category: OneHandWeaponCategory.SPELL_FOCUS,
    cost: 4,
    damage: 0,
    rank: 2,
    weight: 2,
    bonuses: [
      { stat: 'magicDamage', value: 4 },
      { stat: 'magicMastery', value: 5 },
    ],
  },
  {
    id: 110,
    name: 'Crosse tellurique',
    category: OneHandWeaponCategory.SPELL_FOCUS,
    cost: 4,
    damage: 0,
    rank: 3,
    weight: 2,
    bonuses: [
      { stat: 'magicDamage', value: 5 },
      { stat: 'constitution', value: 1 },
    ],
    recipe: [
      { material: 'ebony', value: 4 },
      { material: 'topaz', value: 1 },
    ],
  },
  {
    id: 250,
    name: 'Orbe démon',
    category: OneHandWeaponCategory.SPELL_FOCUS,
    cost: 4,
    damage: 0,
    rank: 3,
    weight: 2,
    element: ElementType.DARK,
    bonuses: [
      { stat: 'magicDamage', value: 6 },
      { stat: 'spirit', value: -2 },
    ],
    recipe: [
      { material: 'blood', value: 3 },
      { material: 'ruby', value: 1 },
    ],
  },
  {
    id: 309,
    name: 'Orbe angélique',
    category: OneHandWeaponCategory.SPELL_FOCUS,
    cost: 4,
    damage: 0,
    rank: 3,
    weight: 2,
    element: ElementType.LIGHT,
    bonuses: [
      { stat: 'magicDamage', value: 2 },
      { stat: 'spirit', value: 2 },
    ],
  },
  {
    id: 289,
    name: 'Sceptre coeur',
    category: OneHandWeaponCategory.SPELL_FOCUS,
    cost: 4,
    damage: 0,
    rank: 3,
    weight: 2,
    bonuses: [
      { stat: 'magicDamage', value: 3 },
      { stat: 'healthRegen', value: 2 },
      { stat: 'intelligence', value: 2 },
    ],
    recipe: [
      { material: 'yew', value: 2 },
      { material: 'ruby', value: 1 },
    ],
  },
  {
    id: 76,
    name: 'Sceptre émeraude',
    category: OneHandWeaponCategory.SPELL_FOCUS,
    cost: 4,
    damage: 0,
    rank: 3,
    weight: 2,
    bonuses: [
      { stat: 'magicDamage', value: 4 },
      { stat: 'magicMastery', value: 10 },
    ],
    recipe: [
      { material: 'wood', value: 3 },
      { material: 'emerald', value: 1 },
    ],
  },
  {
    id: 206,
    name: 'Sceptre en mithril',
    category: OneHandWeaponCategory.SPELL_FOCUS,
    cost: 4,
    damage: 0,
    rank: 3,
    weight: 2,
    bonuses: [
      { stat: 'magicMastery', value: 10 },
      { stat: 'magicDamage', value: 3 },
    ],
    recipe: [
      { material: 'yew', value: 3 },
      { material: 'mithril', value: 2 },
    ],
  },
  {
    id: 290,
    name: 'Sceptre foudre',
    category: OneHandWeaponCategory.SPELL_FOCUS,
    cost: 4,
    damage: 0,
    rank: 3,
    weight: 2,
    element: ElementType.THUNDER,
    bonuses: [{ stat: 'magicDamage', value: 4 }],
    recipe: [
      { material: 'ebony', value: 4 },
      { material: 'topaz', value: 1 },
    ],
  },
  {
    id: 205,
    name: 'Sceptre glace',
    category: OneHandWeaponCategory.SPELL_FOCUS,
    cost: 4,
    damage: 0,
    rank: 3,
    weight: 2,
    element: ElementType.ICE,
    bonuses: [{ stat: 'magicDamage', value: 4 }],
    recipe: [
      { material: 'wood', value: 3 },
      { material: 'sapphire', value: 1 },
    ],
  },
  {
    id: 117,
    name: 'Sceptre lumière',
    category: OneHandWeaponCategory.SPELL_FOCUS,
    cost: 4,
    damage: 0,
    rank: 3,
    weight: 2,
    element: ElementType.LIGHT,
    bonuses: [
      { stat: 'magicDamage', value: 2 },
      { stat: 'observation', value: 10 },
    ],
    recipe: [
      { material: 'yew', value: 2 },
      { material: 'golden_dust', value: 1 },
    ],
  },
  {
    id: 207,
    name: 'Sceptre noble',
    category: OneHandWeaponCategory.SPELL_FOCUS,
    cost: 5,
    damage: 5,
    rank: 3,
    weight: 2,
    bonuses: [{ stat: 'magicDamage', value: 4 }],
    recipe: [
      { material: 'copper', value: 3 },
      { material: 'amber', value: 1 },
    ],
  },
  {
    id: 366,
    name: 'Sceptre de pouvoir',
    category: OneHandWeaponCategory.SPELL_FOCUS,
    cost: 4,
    damage: 0,
    rank: 3,
    weight: 2,
    bonuses: [{ stat: 'magicDamage', value: 6 }],
  },
];
