import { OneHandWeaponCategory, Weapon } from "../../../types";

export const SPELL_RECEPTACLES: Weapon[] = [
  {
    id: 442,
    name: 'Manuel de magie',
    category: OneHandWeaponCategory.SPELL_RECEPTACLE,
    scrolls: 3,
    rank: 2,
    weight: 2,
  },
  {
    id: 231,
    name: 'Brassard runique',
    category: OneHandWeaponCategory.SPELL_RECEPTACLE,
    scrolls: 1,
    rank: 3,
    weight: 2,
    bonuses: [
      { stat: 'armor', value: 1 },
      { stat: 'magicMastery', value: 10 },
    ],
    recipe: [
      { material: 'copper', value: 2 },
      { material: 'blue_fiber', value: 2 },
      { material: 'sapphire', value: 1 },
    ],
  },
  {
    id: 24,
    name: 'Grimoire',
    category: OneHandWeaponCategory.SPELL_RECEPTACLE,
    scrolls: 3,
    rank: 3,
    weight: 2,
    bonuses: [{ stat: 'intelligence', value: 1 }],
    recipe: [
      { material: 'leather', value: 2 },
      { material: 'ink', value: 2 },
      { material: 'sapphire', value: 1 },
    ],
  },
  {
    id: 275,
    name: 'Grimoire astral',
    category: OneHandWeaponCategory.SPELL_RECEPTACLE,
    scrolls: 3,
    rank: 3,
    weight: 2,
    bonuses: [{ stat: 'magicMastery', value: 5 }],
    recipe: [
      { material: 'leather', value: 2 },
      { material: 'ink', value: 2 },
      { material: 'amethyst', value: 1 },
    ],
  },
  {
    id: 227,
    name: 'Livre des morts',
    category: OneHandWeaponCategory.SPELL_RECEPTACLE,
    scrolls: 3,
    rank: 3,
    weight: 2,
    bonuses: [{ stat: 'strength', value: 1 }],
  },
  {
    id: 224,
    name: 'Ouvrage sylvestre',
    category: OneHandWeaponCategory.SPELL_RECEPTACLE,
    scrolls: 3,
    rank: 3,
    weight: 2,
    bonuses: [{ stat: 'dexterity', value: 1 }],
    recipe: [
      { material: 'leather', value: 2 },
      { material: 'ink', value: 2 },
      { material: 'emerald', value: 1 },
    ],
  },
  {
    id: 226,
    name: 'Recueil sacré',
    category: OneHandWeaponCategory.SPELL_RECEPTACLE,
    scrolls: 3,
    rank: 3,
    weight: 2,
    bonuses: [{ stat: 'armor', value: 1 }],
    recipe: [
      { material: 'leather', value: 2 },
      { material: 'ink', value: 2 },
      { material: 'topaz', value: 1 },
    ],
  },
  {
    id: 257,
    name: 'Testament rituel',
    category: OneHandWeaponCategory.SPELL_RECEPTACLE,
    scrolls: 3,
    rank: 3,
    weight: 2,
    bonuses: [{ stat: 'spirit', value: 1 }],
    recipe: [
      { material: 'leather', value: 2 },
      { material: 'ink', value: 2 },
      { material: 'ruby', value: 1 },
    ],
  },
  {
    id: 256,
    name: 'Tome de cristal',
    category: OneHandWeaponCategory.SPELL_RECEPTACLE,
    scrolls: 3,
    rank: 3,
    weight: 2,
    bonuses: [{ stat: 'magicDefense', value: 5 }],
  },
  {
    id: 367,
    name: 'Codex de pouvoir',
    category: OneHandWeaponCategory.SPELL_RECEPTACLE,
    scrolls: 3,
    rank: 3,
    weight: 2,
    bonuses: [{ stat: 'magicDamage', value: 1 }],
  },
  {
    id: 428,
    name: 'Carnet de novice',
    category: OneHandWeaponCategory.SPELL_RECEPTACLE,
    scrolls: 2,
    rank: 1,
    weight: 2,
  },
];
