import { ElementType, OneHandWeaponCategory, Weapon } from "../../../types";

export const SWORDS: Weapon[] = [
  {
    id: 1,
    name: 'Epée courte',
    category: OneHandWeaponCategory.SWORD,
    cost: 4,
    damage: 4,
    rank: 1,
    weight: 2,
    recipe: [{ material: 'iron', value: 2 }],
  },
  {
    id: 56,
    name: 'Glaive',
    category: OneHandWeaponCategory.SWORD,
    cost: 4,
    damage: 5,
    rank: 2,
    weight: 2,
    recipe: [{ material: 'copper', value: 2 }],
  },
  {
    id: 114,
    name: 'Lame',
    category: OneHandWeaponCategory.SWORD,
    cost: 5,
    damage: 7,
    rank: 2,
    weight: 2,
    recipe: [{ material: 'iron', value: 4 }],
  },
  {
    id: 328,
    name: 'Badelaire Ardent',
    category: OneHandWeaponCategory.FIRE_SWORD,
    cost: 5,
    damage: 4,
    rank: 3,
    weight: 2,
    element: ElementType.FIRE,
    effects: [{ status: 'burn', value: 2 }]
  },
  {
    id: 27,
    name: 'Barong',
    category: OneHandWeaponCategory.SWORD,
    cost: 5,
    damage: 5,
    rank: 3,
    weight: 2,
    effects: [{ status: 'bleeding', value: 2 }],
    recipe: [
      { material: 'iron', value: 3 },
      { material: 'blood', value: 1 },
    ],
  },
  {
    id: 204,
    name: 'Cimeterre',
    category: OneHandWeaponCategory.SWORD,
    cost: 4,
    damage: 6,
    rank: 3,
    weight: 2,
    recipe: [
      { material: 'iron', value: 3 },
      { material: 'copper', value: 3 },
    ],
  },
  {
    id: 316,
    name: 'Epée cauchemar',
    category: OneHandWeaponCategory.SWORD,
    cost: 4,
    damage: 3,
    effects: [{ status: 'magic_defense_penalty', value: 1 }],
    rank: 3,
    weight: 2,
  },
  {
    id: 100,
    name: 'Epée de spadassin',
    category: OneHandWeaponCategory.SWORD,
    cost: 4,
    damage: 4,
    rank: 3,
    weight: 2,
    bonuses: [{ stat: 'precision', value: 10 }],
    recipe: [{ material: 'iron', value: 4 }],
  },
  {
    id: 136,
    name: 'Epée noble',
    category: OneHandWeaponCategory.SWORD,
    cost: 4,
    damage: 4,
    rank: 3,
    weight: 2,
    bonuses: [{ stat: 'intelligence', value: 2 }],
    recipe: [
      { material: 'copper', value: 3 },
      { material: 'amber', value: 1 },
    ],
  },
  {
    id: 119,
    name: 'Falchion',
    category: OneHandWeaponCategory.SWORD,
    cost: 5,
    damage: 9,
    rank: 3,
    weight: 2,
    recipe: [{ material: 'iron', value: 6 }],
  },
  {
    id: 252,
    name: 'Lame solaire',
    category: OneHandWeaponCategory.SWORD,
    cost: 5,
    damage: 6,
    rank: 3,
    weight: 2,
    element: ElementType.LIGHT,
    recipe: [
      { material: 'copper', value: 3 },
      { material: 'golden_dust', value: 1 },
    ],
  },
  {
    id: 196,
    name: 'Langue démon',
    category: OneHandWeaponCategory.SWORD,
    cost: 6,
    damage: 3,
    rank: 3,
    weight: 2,
    effects: [{ status: 'necrosis', value: 2 }],
    recipe: [
      { material: 'iron', value: 4 },
      { material: 'blood', value: 2 },
    ],
  },
  {
    id: 311,
    name: 'Main-gauche',
    category: OneHandWeaponCategory.DAGGER,
    cost: 4,
    damage: 3,
    rank: 3,
    weight: 2,
    bonuses: [{ stat: 'evasion', value: 5 }],
    recipe: [
      { material: 'iron', value: 2 },
      { material: 'amethyst', value: 1 },
    ],
  },
  {
    id: 364,
    name: 'Crépusculaire',
    category: OneHandWeaponCategory.SWORD,
    cost: 5,
    damage: 4,
    rank: 3,
    weight: 2,
    element: ElementType.DARK,
    effects: [{ status: 'accuracy_penalty', value: 2 }],
  },
];
