import { Material, MaterialKey } from "../types";

export const MATERIALS: Record<MaterialKey, Material> = {
  amber: { id: 144, name: 'Ambre' },
  amethyst: { id: 176, name: 'Gemme améthyste' },
  black_powder: { id: 343, name: 'Poudre noire' },
  blood: { id: 210, name: 'Sang' },
  blue_fiber: { id: 143, name: 'Fibre bleue' },
  copper: { id: 171, name: 'Minerai de cuivre' },
  diamond: { id: 341, name: 'Gemme diamant' },
  ebony: { id: 338, name: 'Ebène' },
  emerald: { id: 174, name: 'Gemme émeraude' },
  fairy_wing: { id: 295, name: 'Aile de fée' },
  feather: { id: 70, name: 'Plume' },
  golden_dust: { id: 302, name: 'Poussière dorée' },
  ink: { id: 342, name: 'Encre' },
  iron: { id: 90, name: 'Minerai de fer' },
  ivy: { id: 219, name: 'Lierre' },
  leaf: { id: 211, name: 'Feuille' },
  leather: { id: 6, name: 'Cuir' },
  mithril: { id: 254, name: 'Minerai de mithril' },
  purple_fiber: { id: 142, name: 'Fibre violette' },
  rock: { id: 35, name: 'Pierre' },
  ruby: { id: 172, name: 'Gemme rubis' },
  sapphire: { id: 175, name: 'Gemme saphir' },
  scales: { id: 220, name: 'Ecailles' },
  sewing_thread: { id: 223, name: 'Fil à coudre' },
  sinew: { id: 72, name: 'Tendon' },
  teeth: { id: 67, name: 'Dents' },
  topaz: { id: 173, name: 'Gemme topaze' },
  wood: { id: 5, name: 'Planche de bois' },
  yew: { id: 262, name: 'If' },
};
