import { ElementType, TwoHandWeaponCategory, Weapon } from "../../../types";

export const TWO_HAND_BOWS: Weapon[] = [
  {
    id: 363,
    name: 'Arc funeste',
    category: TwoHandWeaponCategory.BOW,
    cost: 5,
    range: { min: 2, max: 3 },
    damage: 6,
    rank: 3,
    weight: 2,
    element: ElementType.DARK,
    effects: [{ status: 'accuracy_penalty', value: 1 }],
  },
  {
    id: 39,
    name: 'Arc court',
    category: TwoHandWeaponCategory.BOW,
    cost: 4,
    range: { min: 2, max: 3 },
    damage: 4,
    rank: 1,
    weight: 2,
    recipe: [
      { material: 'wood', value: 1 },
      { material: 'sinew', value: 1 },
    ],
  },
  {
    id: 127,
    name: 'Arc de chasseur',
    category: TwoHandWeaponCategory.BOW,
    cost: 4,
    range: { min: 2, max: 3 },
    damage: 5,
    rank: 2,
    weight: 2,
    recipe: [
      { material: 'wood', value: 1 },
      { material: 'sinew', value: 1 },
    ],
  },
  {
    id: 128,
    name: 'Arc composite',
    category: TwoHandWeaponCategory.BOW,
    cost: 5,
    range: { min: 2, max: 3 },
    damage: 7,
    rank: 2,
    weight: 2,
  },
  {
    id: 163,
    name: 'Arc béni',
    category: TwoHandWeaponCategory.BOW,
    cost: 5,
    range: { min: 2, max: 3 },
    damage: 6,
    rank: 3,
    weight: 2,
    element: ElementType.LIGHT,
    bonuses: [{ stat: 'intelligence', value: 2 }],
    recipe: [
      { material: 'yew', value: 4 },
      { material: 'sinew', value: 1 },
      { material: 'golden_dust', value: 1 },
    ],
  },
  {
    id: 109,
    name: 'Arc de guerre',
    category: TwoHandWeaponCategory.BOW,
    cost: 5,
    range: { min: 2, max: 3 },
    damage: 7,
    rank: 3,
    weight: 2,
    effects: [{ status: 'bleeding', value: 1 }],
    recipe: [
      { material: 'ebony', value: 2 },
      { material: 'sinew', value: 1 },
      { material: 'teeth', value: 1 },
    ],
  },
  {
    id: 230,
    name: 'Arc de rôdeur',
    category: TwoHandWeaponCategory.BOW,
    cost: 4,
    range: { min: 2, max: 3 },
    damage: 4,
    rank: 3,
    weight: 2,
    bonuses: [{ stat: 'dexterity', value: 2 }],
    recipe: [
      { material: 'ebony', value: 3 },
      { material: 'ivy', value: 2 },
      { material: 'leaf', value: 2 },
    ],
  },
  {
    id: 294,
    name: "Arc d'élite",
    category: TwoHandWeaponCategory.BOW,
    cost: 5,
    range: { min: 2, max: 3 },
    damage: 7,
    rank: 3,
    weight: 2,
    effects: [{ status: 'armor_penalty', value: 1 }],
    recipe: [
      { material: 'ebony', value: 2 },
      { material: 'sinew', value: 2 },
    ],
  },
  {
    id: 17,
    name: 'Arc lourd composite',
    category: TwoHandWeaponCategory.BOW,
    cost: 5,
    range: { min: 2, max: 3 },
    damage: 9,
    rank: 3,
    weight: 2,
    recipe: [
      { material: 'wood', value: 5 },
      { material: 'sinew', value: 2 },
    ],
  },
  {
    id: 79,
    name: 'Arc sylvain',
    category: TwoHandWeaponCategory.BOW,
    cost: 5,
    range: { min: 2, max: 3 },
    damage: 6,
    rank: 3,
    weight: 2,
    bonuses: [{ stat: 'precision', value: 15 }],
    recipe: [
      { material: 'yew', value: 3 },
      { material: 'ivy', value: 2 },
      { material: 'leaf', value: 2 },
    ],
  },
];
