import { TwoHandWeaponCategory, Weapon } from "../../../types";

export const TWO_HAND_SWORDS: Weapon[] = [
  {
    id: 10,
    name: 'Epée large',
    category: TwoHandWeaponCategory.SWORD,
    cost: 4,
    damage: 5,
    rank: 1,
    weight: 4,
    recipe: [{ material: 'iron', value: 4 }],
  },
  {
    id: 448,
    name: 'Espadon',
    category: TwoHandWeaponCategory.SWORD,
    cost: 4,
    damage: 7,
    rank: 2,
    weight: 4,
  },
  {
    id: 246,
    name: 'Epée géante',
    category: TwoHandWeaponCategory.SWORD,
    cost: 5,
    damage: 9,
    rank: 2,
    weight: 4,
    recipe: [{ material: 'iron', value: 6 }],
  },
  {
    id: 122,
    name: 'Claymore',
    category: TwoHandWeaponCategory.SWORD,
    cost: 5,
    damage: 10,
    rank: 3,
    weight: 5,
    bonuses: [{ stat: 'precision', value: 10 }],
    recipe: [
      { material: 'iron', value: 5 },
      { material: 'diamond', value: 1 },
    ],
  },
  {
    id: 245,
    name: 'Guillotineuse',
    category: TwoHandWeaponCategory.SWORD,
    cost: 5,
    damage: 10,
    rank: 3,
    weight: 5,
    bonuses: [{ stat: 'evasion', value: 10 }],
    recipe: [
      { material: 'iron', value: 5 },
      { material: 'blood', value: 2 },
    ],
  },
  {
    id: 147,
    name: 'Flamberge',
    category: TwoHandWeaponCategory.SWORD,
    cost: 5,
    damage: 12,
    rank: 3,
    weight: 5,
    recipe: [
      { material: 'iron', value: 4 },
      { material: 'copper', value: 4 },
    ],
  },
];
